name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lua files
        run: zip -9 -r game.love . -x ".git/*" ".github/*"

      - name: Build APK with Love2D
        uses: pmaru/love2d-android-build-action@v1.1
        with:
          love_file: game.love
          app_name: "MyClickerGame"
          package_name: "com.yourname.clicker"

      - name: Upload APK
        uses: actions/actions-upload-artifact@v3
        with:
          name: my-game-apk
          path: "*.apk"