name: Build Android APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Упаковываем файлы игры в .love
      - name: Zip Lua files
        run: |
          zip -9 -r game.love . -x ".git/*" ".github/*"

      # Используем официальный способ сборки через Love2D-Android
      - name: Build APK
        uses: love2d-community/love-android-action@v1
        with:
          love_file: game.love
          app_name: "MyClickerGame"
          package_name: "com.kasval.clicker"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-game-apk
          path: "**/*.apk"